name: Milestone Management

on:
  workflow_dispatch:

jobs:
  manage-milestones:
    runs-on: ubuntu-latest
    steps:
      - name: Close "Next Release" milestone
        id: close_milestone
        uses: Akkjon/close-milestone@v1
        with:
          milestone_name: 'Next Release'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: print
        run: echo ${{ steps.close_milestone.outputs.milestone_id }}
      - name: Rename milestone (even if closed)
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/milestones/${{ steps.close_milestone.outputs.milestone_id }}
          parameters: |
            title: "Version 123"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Output renamed milestone URL
        run: |
          echo "Renamed milestone URL: https://github.com/${{ github.repository }}/milestone/${{ steps.close_milestone.outputs.milestone_id }}"

      - name: Create new "Next Release" milestone
        uses: WyriHaximus/github-action-create-milestone@v1.1.2
        with:
          title: 'Next Release'
          description: ${{ github.event.inputs.new_milestone_description }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
