name: Milestone Management

on:
  workflow_dispatch:

jobs:
  manage:
    runs-on: ubuntu-latest
    steps:
      - name: Get all milestones
        id: get_milestones
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/milestones?state=open
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Extract milestone ID
        id: extract
        run: |
          echo '${{ steps.get_milestones.outputs.data }}' | jq '.[] | select(.title == "Next Release") | .number' > id.txt
          milestone_id=$(cat id.txt)
          echo "milestone_id=$milestone_id" >> $GITHUB_OUTPUT
        shell: bash

      - name: Rename and close milestone
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/milestones/${{ steps.extract.outputs.milestone_id }}
          parameters: |
            title: "New Version"
            state: closed
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Output renamed milestone URL
        run: |
          echo "Renamed milestone URL: https://github.com/${{ github.repository }}/milestone/${{ steps.extract.outputs.milestone_id }}"

      - name: Create new "Next Release" milestone
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/milestones
          parameters: |
            title: Next Release
            description: ${{ github.event.inputs.new_milestone_description }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
